# Create a new namespace called dev
kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
# Create a new Role called dev-all, with full access to app apiGroups and all resources inside of Namespace dev
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: dev
  name: dev-all
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
# Create a new RoleBinding called dev-role-dev-all-members that binds the Role dev-all to Github group SENamespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: dev-role-dev-all-members
  namespace: dev
subjects:
  - kind: Group
    # this needs to match your GitHub group name
    name: SENamespace
roleRef:
  kind: Role
  name: dev-all
  apiGroup: "rbac.authorization.k8s.io"
---
# Create a new ClusterRole called list-ns-all, that only has access to list namespaces
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: list-ns-all
rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - namespaces/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
---
# Create a new ClusterRoleBinding called cluster-role-list-ns-all-members, that binds the role list-ns-all to authenticated users
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-role-list-ns-all-members
subjects:
  - kind: Group
    name: system:authenticated
roleRef:
  kind: ClusterRole
  name: list-ns-all
  apiGroup: "rbac.authorization.k8s.io"
---
# That will use the system:discovery ClusterRole and bind all users (authenticated and unauthenticated) to it, allowing them to access 
# swagger and API group information.

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-role-all-discover-api
subjects:
  - kind: Group
    name: system:authenticated
  - kind: Group
    name: system:unauthenticated
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: "rbac.authorization.k8s.io"